pubky/pubky-core

pubky/src/shared/auth.rs

- Previously, the request function returned `Ok(())` even if the HTTP response status was an error (4xx/5xx). By adding `response.error_for_status()?`, we correctly propagate HTTP errors rather than masking them, ensuring that timeouts and other non-2xx status codes produce an error as expected.

fix: return an error for non-2xx responses using error_for_status()

---

Dockerfile
examples/authz/3rd-party-app/src/pubky-auth-widget.js
pubky/pkg/test/auth.js
pubky/src/shared/auth.rs

Still defaults to x86. Pass build arg when using ARM architecture: `docker build --build-arg TARGETARCH=aarch64 .`

fix: ARM (Apple Silicon) build support in Dockerfile

---

examples/Cargo.toml
pubky-homeserver/README.md
pubky/README.md

As we mostly use `cargo nextest run` , we stoped testing our readmes, as it seems only `cargo test` is now running those snippets. As consequence, the readmes have been outdated/untested for some time.
This fixes `cargo test` . Therefore it seems introducing `tokio-shared-rt` is not necessary as seen in https://github.com/pubky/pubky-core/pull/71

fix(tests): update apis on docs

---

.github/workflows/pr-check.yml

Some crates were testing 0 tests. For example `pubky-testnet` only test is the Readme snippet. This is because `cargo nextest` does not support doctests yet. We can run `cargo test --docs` sequentially. This can be simplified in the future if `cargo nextest` starts to support doctests.

chore: add doctests to CI

---

pubky-testnet/src/lib.rs

This PR reduces the number of Dht testnet nodes from 10 to 3. 
Both should suffice for testing. But 3 might improve start up times in some specific environments where `mainline::Testnet` after the `5.3.1` fix still takes a considerable amount of time to start for some unknown reason. More context in https://github.com/pubky/mainline/issues/52#issuecomment-2676219391

fix: improve testnet start up times in some environments

---

examples/authn/README.md
examples/authn/signup.rs
examples/authz/authenticator.rs
pubky-homeserver/README.md
pubky-homeserver/src/config.example.toml
pubky-homeserver/src/config.rs
pubky-homeserver/src/core/database/migrations/m0.rs
pubky-homeserver/src/core/database/tables.rs
pubky-homeserver/src/core/database/tables/entries.rs
pubky-homeserver/src/core/database/tables/signup_tokens.rs
pubky-homeserver/src/core/database/tables/users.rs
pubky-homeserver/src/core/layers/admin.rs
pubky-homeserver/src/core/layers/mod.rs
pubky-homeserver/src/core/mod.rs
pubky-homeserver/src/core/routes/admin.rs
pubky-homeserver/src/core/routes/auth.rs
pubky-homeserver/src/core/routes/mod.rs
pubky-homeserver/src/io/mod.rs
pubky-testnet/src/lib.rs
pubky/README.md
pubky/pkg/README.md
pubky/pkg/package.json
pubky/pkg/test/auth.js
pubky/pkg/test/public.js
pubky/pkg/test/utils.js
pubky/src/native/api/auth.rs
pubky/src/native/api/public.rs
pubky/src/wasm/api/auth.rs

feat: signup tokens

---

.github/workflows/pr-check.yml

`pkarr-republisher` tests were not run on Github. This adds the tests.

fix (pkarr-republisher): Include in Github workflow

---

e2e/src/tests/public.rs
pubky-homeserver/src/core/layers/pubky_host.rs

A simple fix so the `pubky-host` header, if missing, can be extracted from the URL. So in addition of this working
```bash
curl -H "pubky-host: b8pf41opxrtgwjox7a49u6d677snmutyukzdy5wdueet5sne4q8o" https://homeserver.pubky.app/pub/pubky.app/profile.json
```
this would also work
```
curl https://homeserver.pubky.app/pub/pubky.app/profile.json&pubky-host=b8pf41opxrtgwjox7a49u6d677snmutyukzdy5wdueet5sne4q8o
```
Useful for fetching data from contexts where headers cannot be set.

feat(homeserver): fallback missing pubky-host header to query param

---

pubky-homeserver/src/data_directory/config_toml.rs
pubky-homeserver/src/data_directory/signup_mode.rs

Remove `unwrap()` in SignupMode and uses more serde(default) macros to simplify the code.
`Display` is still there for debug/optic purposes.

fix(homeserver): simplified config with serde(default)

---

Cargo.lock
pubky-homeserver/src/core/homeserver_core.rs
pubky-homeserver/src/data_directory/persistent_data_dir.rs
pubky-testnet/Cargo.toml
pubky-testnet/src/ephemeral_testnet.rs
pubky-testnet/src/main.rs
pubky-testnet/src/static_testnet.rs

Adds the ability to run the `StaticTestnet` binary with a custom homeserver config
```bash
cargo run -- --homeserver-config=config.toml  
```
The old way still works too
```bash
cargo run
```
In both ways, the data is not persisted after the binary is stopped.

feat: add --homeserver-config arg to testnet binary

---

pubky-homeserver/src/data_directory/config_toml.rs

All config values are optional but the headers (`[general]`) aren't. This PR makes them optional too. This way, an empty config file is a valid config too.

feat: Make config headers optional

---

pubky-homeserver/config.default.toml
pubky-homeserver/src/data_directory/config_toml.rs

For easier local testing, I set the default `icann_domain` from previously `None` to `Some("localhost")`.
FYI @catch-21

feat(homeserver): Set default icann_domain to localhost

---

e2e/src/tests/auth.rs
pubky-homeserver/src/admin/app.rs
pubky-homeserver/src/admin/routes/delete_entry.rs
pubky-homeserver/src/admin/routes/disable_users.rs
pubky-homeserver/src/admin/routes/mod.rs
pubky-homeserver/src/core/err_if_user_is_invalid.rs
pubky-homeserver/src/core/mod.rs
pubky-homeserver/src/core/routes/auth.rs
pubky-homeserver/src/core/routes/tenants/read.rs
pubky-homeserver/src/core/routes/tenants/session.rs
pubky-homeserver/src/core/routes/tenants/write.rs
pubky-homeserver/src/core/user_keys_republisher.rs
pubky-homeserver/src/lib.rs
pubky-homeserver/src/persistence/lmdb/db.rs
pubky-homeserver/src/persistence/lmdb/migrations/m220420251247_add_user_disabled.rs
pubky-homeserver/src/persistence/lmdb/migrations/m220420251247_add_user_disabled_used_bytes.rs
pubky-homeserver/src/persistence/lmdb/migrations/mod.rs
pubky-homeserver/src/persistence/lmdb/tables/users.rs
pubky-homeserver/src/shared/http_error.rs
pubky-homeserver/src/shared/mod.rs
pubky-homeserver/src/shared/pubkey_path_validator.rs

Adds the following endpoints to the admin interface:
- `Delete entry` - Deletes a specific file. Adds a delete event
- `Disable user` - Disables a user. Prevents them from sign in and to read/write any files from this specific user.
- `Enable user` - Enables a disabled user.
Migrates the `User` entity, adds the `disabled` field.
I had to suppress an inner urge to refactor the core web server and lmdb. So most of this code is structured as good as it gets in consideration of the surrounding environment.
Adds `used_bytes` to the user migration for #108.

feat(homeserver): Admin delete entry + ban user endpoints

---

e2e/src/tests/auth.rs
pubky-client/pkg/test/utils.js
pubky-homeserver/src/admin/app.rs

Newly added admin endpoints added in #110 are not password protected. This PR fixes this.

fix(homeserver): move exposed admin endpoints behind pw protection

---

pubky-homeserver/src/admin/app.rs
pubky-homeserver/src/admin/routes/info.rs
pubky-homeserver/src/admin/routes/mod.rs

Simple admin info endpoint on `/info` that returns:
```
num_users: u64,
num_disabled_users: u64,
total_disk_used_mb: f64,
num_signup_codes: u64,
num_unused_signup_codes: u64,
```

feat(homeserver): add info endpoint

---

e2e/src/tests/auth.rs
pubky-homeserver/src/core/err_if_user_is_invalid.rs
pubky-homeserver/src/core/routes/auth.rs
pubky-homeserver/src/core/routes/tenants/read.rs
pubky-homeserver/src/core/routes/tenants/session.rs
pubky-homeserver/src/core/routes/tenants/write.rs

This changes the homeservers behaviour when a user is disabled.
- A disabled user can still login, create sessions, read, and delete all their files.
- A disabled user can NOT write files anymore.
FYI @dzdidi

feat: Only block disabled users from writing files, not reading

---

CONTRIBUTORS.md
Cargo.lock
Cargo.toml
README.md
e2e/Cargo.toml
examples/Cargo.toml
http-relay/Cargo.toml
pkarr-republisher/Cargo.toml
pubky-client/Cargo.toml
pubky-client/src/lib.rs
pubky-common/Cargo.toml
pubky-homeserver/Cargo.toml
pubky-testnet/Cargo.toml

- Unifies the versioning of all workspace members to the top level Cargo.toml.
- New version `0.5.0-rc.0`.
- Added contributors guide similar to [Blocktank](https://github.com/synonymdev/blocktank-lsp-ln2/blob/master/CONTRIBUTORS.md).
I already published the new `0.5.0-rc.0` version on crates to test the workflow. I will create the Github release with the release notes after this PR is merged.
@SHAcollision Please check the guide as this will be new for pubky.

chore (repo): Version Unification

---

README.md

Fixes the links for the crates version and the github license

chore(general): Main readme links

---

Cargo.lock
e2e/src/tests/rate_limiting.rs
pubky-homeserver/Cargo.toml
pubky-homeserver/config.sample.toml
pubky-homeserver/src/core/layers/rate_limiter/layer.rs
pubky-homeserver/src/data_directory/quota_config/http_method.rs
pubky-homeserver/src/data_directory/quota_config/limit_key.rs
pubky-homeserver/src/data_directory/quota_config/mod.rs
pubky-homeserver/src/data_directory/quota_config/path_limit.rs

Adds the ability to add a whitelist to rate limits.
Examples:
```toml
[[drive.rate_limits]]
path = "/session"
method = "POST"
quota = "20r/m"
key = "ip"
whitelist = [
"127.0.0.1"
]
[[drive.rate_limits]]
path = "/pub/**" 
method = "PUT"
quota = "1mb/s"
key = "user"
burst = 10
whitelist = [
"8pinxxgqs41n4aididenw5apqp1urfmzdztr8jt4abrkdn435ewo"
]
```
The whitelist is fully validated on ConfigToml parse. 
- It either is a valid pubkey or a IP address.
- Whitelist element must match the rate limit key type.
Includes an end2end test.

feat(homeserver): Whitelist for rate limits

---

pubky-homeserver/src/homeserver_suite/suite.rs
pubky-homeserver/src/lib.rs
pubky-homeserver/src/main.rs
pubky-homeserver/src/tracing.rs

This PR allows the `main` method to init tracing early. With #138, any logs before the homeserver suite start were hidden. This included the config parsing.
This PR fixes this and exposes a new `init_tracing_logs_if_set` method so anybody can initialize the logs early.

fix(homeserver): Allow early tracing init to catch early errors

---

.github/workflows/pr-check.yml
pubky-common/src/capabilities.rs
pubky-homeserver/src/core/layers/authz.rs
pubky-homeserver/src/shared/http_error.rs

We get random logouts with a 404 Not Found error when calling /session. This PR improves the http response message in this case + adds logs.
I had to fix the rust version for the pipeline to 1.87. The new rust 1.88 adds new clippy warnings that I didn't want to fix in this PR.
FYI: @catch-21

chore(hs): Improved session auth failed reasons and logs

---

e2e/src/tests/auth.rs
pubky-homeserver/src/core/routes/auth.rs

The homeserver returns a HTTP `500` Internal Server Error when the signup token is invalid but required.
This PR turns it into a `401` Unauthorized + improved test.
FYI @catch-21

fix(hs): Return 401 instead of a 500 when the signup token is invalid

---

e2e/src/tests/auth.rs
pubky-homeserver/src/core/routes/auth.rs
pubky-homeserver/src/persistence/lmdb/tables/signup_tokens.rs

This PR makes sure to return "Token already used" message when a signup token has already been used. It also adds a test to check this.
FYI @catch-21

fix(hs): signup token error message

---

pubky-homeserver/src/core/layers/rate_limiter/layer.rs

In case the `pubky-host` can't be extracted, the rate limiter returns an error. Before, this was a `500`. James run into this recently. This should be a `400 BAD REQUEST` though because it's the users fault not sending the pubky-host to the server.
FYI @catch-21

chore(hs): rate limit key extraction change http code

---

pubky-homeserver/src/core/routes/auth.rs

Reverts pubky/pubky-core#174
This doesn't work for @flaviomoceri when he is running pubky-app on localhost and uses the staging backend. Reverting.

Revert "fix(hs): Cookie Samesite Strict"

---

pubky-homeserver/src/core/key_republisher.rs

Turns out that SVCB priority of `0` has a [special meaning](https://kb.isc.org/docs/svcb-and-https-resource-records-what-are-they) similar to a cname. This PR changes the priority to `1` to comply with the standard.

fix(hs): SVCB priority

---

pubky-client/bindings/js/src/constructor.rs
pubky-client/src/api/http.rs
pubky-client/src/client.rs
pubky-homeserver/src/core/routes/auth.rs
pubky-testnet/src/static_testnet.rs

This PR introduces several changes to improve the flexibility of the testnet environment, allowing it to run seamlessly within a Docker-based setup while maintaining backward compatibility with existing `localhost` development workflows.
This work was originally proposed and implemented by @SpontaneousOverthrow here https://github.com/pubky/pubky-core/commit/26bd8423f3fc380cd64c812575c7d1cb22ef7454  to address issues with service discovery in our containerized testnet. 
Previously, the testnet configuration was hardcoded to use `localhost` for service and relay addresses. While this works for local development, it prevents services from communicating within a Docker network, where containers are typically accessed via their service names (e.g., `homeserver`). In other words, any testnet …

feat(client/testnet): make testnet relay host configurable for Docker

---

Cargo.lock
pubky-homeserver/Cargo.toml
pubky-homeserver/src/persistence/files/entry_layer.rs
pubky-homeserver/src/persistence/files/user_quota_layer.rs

Attempting to fix  https://github.com/pubky/pubky-nexus/actions/runs/16568273872/job/46853557170?pr=513
For some reason direct dependency on `opendal` and transient dependencies on `opendal` get into conflict when we import and use `pubky-testnet` .
In this PR I bump version of both `opendal` and `dav-server-opendalfs` .
Opendal 0.54 has a breaking change that I have sorted by "simply removing it" which helped me confirm compilation is OK and test suites of downstream crates now pass https://github.com/pubky/pubky-nexus/actions/runs/16569835925/job/46858827162?pr=513
However, "simply removing it" might have altered the behavior of the homeserver. Invoking @SeverinAlexB for a more in depth check of this `opendal` breaking change.

chore(deps): bump opendal to 0.54

---

pubky-homeserver/config.sample.toml

Simple comment fix that clarifies the purpose of `public_ip` field.

Update comment in `config.sample.toml`

---

e2e/src/tests/auth.rs
e2e/src/tests/http.rs
e2e/src/tests/public.rs
e2e/src/tests/rate_limiting.rs
examples/authn/signup.rs
examples/authz/authenticator.rs
examples/request/main.rs
pubky-client/README.md
pubky-client/src/client.rs
pubky-testnet/README.md
pubky-testnet/src/ephemeral_testnet.rs
pubky-testnet/src/static_testnet.rs
pubky-testnet/src/testnet.rs

This PR re-introduces two convenience methods for instantiating the `pubky::Client`, improving the developer experience by providing clear, idiomatic entry points for the most common use cases.
```rust
// Creates a client configured for public mainline DHT and pkarr relays.
let client = pubky::Client::default();
```
```rust
// Creates a client configured to talk to a local testnet running on `localhost`.
let client = pubky::Client::testnet();
```
**Why This Change?**
Previously, creating a client required using the builder pattern even for the most standard configurations. While the builder is powerful for custom setups, it adds unnecessary boilerplate for simple use cases. These two methods used to be available in very early versions of `pubky-client` crate.
Also updated **examples**, …

feat(client): add convenience constructors

---

Cargo.lock
Cargo.toml
pubky-homeserver/src/data_directory/persistent_data_dir.rs

The "read-/write-keypair" logic has been outsourced to `pkarr` in https://github.com/pubky/pkarr/pull/166 , essentially by moving that code from this crate to `pkarr`.
This PR removes the outsourced code and re-uses the new methods of `pkarr`.

Re-use read-/write-keypair from updated `pkarr`

---

e2e/src/tests/auth.rs
pubky-testnet/src/ephemeral_testnet.rs
pubky-testnet/src/static_testnet.rs
pubky-testnet/src/testnet.rs

Running multiple ephemeral testnets makes it difficult to test the nexus watcher layer. We need a way to track all homeservers, and having a hardcoded homeserver keypair makes this difficult

feat: ephemeral testnet with random keypair
